### ISSUE TITLE
Question about the default stride

### ISSUE THREAD

**Issue by StarCycle** [1x-technologies/1xgpt#13]
Hi @ericjang @molysgaard @bernob @Guitaricet @JoelFilho,

The default `stride` [here](https://github.com/1x-technologies/1xgpt/blob/45451356bfbbaa480e075fe62734bb61c206fe02/train.py#L59) is 15 and the dataset is 2Hz. So the interval between 2 frames is 7.5 second? Is this interval too large or I miss something?

Best,
StarCycle

**Comment by kev-zhao** [comment]
Hi StarCycle,

The dataset is 30 Hz, so the default `stride` of 15 gives 2 Hz videos.

**Comment by StarCycle** [comment]
I see! Thanks!
