### ISSUE TITLE
Reproducing the baseline for 1x genie

### ISSUE THREAD

**Issue by walsvid** [1x-technologies/1xgpt#16]
Hi all, I have a question regarding reproducing the baseline for 1x genie:

I'm trying to reproduce the baseline results for 1x genie, but I'm encountering difficulties. Using only the command in README:

```
python train.py --genie_config genie/configs/magvit_n32_h8_d256.json --output_dir data/genie_model --max_eval_steps 10
```

It appears that I'm unable to reproduce the baseline performance metrics. The training configuration of the models magvit_n32_h8_d256, GENIE_35M, or GENIE_138M seems to be different.

Apart from using the config.json for STMaskGIT from the model card on HuggingFace, I'm wondering if there are more specific configurations for hyperparameters e.g. `lr_scheduler_type`, `num_warmup_steps`, and `max_grad_norm`?

Is there a more detailed set of configurations that could help me reproduce at least the baseline results? Any additional information or guidance would be greatly appreciated.

Thank you in advance for your help!😀

**Comment by kev-zhao** [comment]
Hi walsvid,

Here are some hyperparameters we used that are different from the defaults in `train.py`, but note that the baseline was trained on additional internal data:

```
--learning_rate 5e-4
--num_warmup_steps 1000
--adam_beta_2 0.95
--lr_scheduler_type cosine
--mu_transfer
--filter_overlaps
```

Our effective batch size was `64`, and `genie_config` should match the `config.json` from HuggingFace, as you noted.

**Comment by walsvid** [comment]
Hi @kev-zhao, thank you for your reply. I'm wondering if training is only needed for 1 epoch. I noticed that the default setting in train.py seems to specify training for only 1 epoch.

**Comment by kev-zhao** [comment]
To clarify, I would think about this codebase as a nice starting point or reference for experiments (e.g. we found no public Genie implementation when this code was released). I would not expect to perfectly reproduce the checkpoints, given that the internal setup was different and possibly included tweaks we found to further improve performance 👀.
