### ISSUE TITLE
Can we get the original images instead of just tokens?

### ISSUE THREAD

**Issue by sami-bg** [1x-technologies/1xgpt#21]
Would it be possible to provide the original images in addition to the image tokens? I'm hoping to experiment with a different encoder and I'm worried that reconstructing the images with magvit2 would remove a lot of noise that would be important in its evaluation.

**Comment by arcelien** [comment]
https://github.com/1x-technologies/1xgpt/issues/3 still applies at this time unfortunately - we're still not ready yet to release raw images; let us know if there are any alternate tokenizers you think would work better
