### ISSUE TITLE
Would you like to update your baseline to newer tokenizer of Open-MAGVIT2?

### ISSUE THREAD

**Issue by StarCycle** [1x-technologies/1xgpt#22]
Hi @molysgaard @ericjang @Guitaricet,

[OpenMagViT](https://github.com/TencentARC/Open-MAGVIT2) just updated their models. They also design a special "intra-token transformer" to deal with large vocabulary problem. Would you like to update your baseline?

Best wishes,
Zhuoheng

**Comment by ericjang** [comment]
Hi! we'll be releasing the dataset with a new tokenizer soon that should improve the overall compression rate while also improving visual quality
