### ISSUE TITLE
Would you like to provide the raw images instead of vector quantinized ones?

### ISSUE THREAD

**Issue by StarCycle** [1x-technologies/1xgpt#3]
Hello,

Would you like to provide the raw images instead of vector quantinized ones? Then we can freely choose other image tokenizer that encodes images to fewer tokens (and thus much quicker image generation).

Best,
StarCycle

**Comment by kev-zhao** [comment]
Hello StarCycle,

We are currently considering releasing raw images, but there are privacy concerns and other issues we have to work out. We are also internally working on a better tokenizer. We hope to have more information within 2 weeks.

**Comment by StarCycle** [comment]
@kev-zhao,

Thank you for response!

There are 2 toknizers you may be interested in:

- [OpenMagViT2](https://github.com/TencentARC/Open-MAGVIT2). Reproduction of magvit2 but it's open-source. Current SOTA in resonstruction quality (well, still worse than Google's)
- [TiTok](https://github.com/bytedance/1d-tokenizer). Recent 1d toknizer that compress 1 image to 32 tokens. They claim to generate >100 images in 1 second with this tokenizer so it may be suitable for **robot world model**.

**Comment by kev-zhao** [comment]
Thank you for the suggestions, we are/will look into these tokenizers!

**Comment by StarCycle** [comment]
And sorry...

I should mention Bytedance's [VAR](https://github.com/FoundationVision/VAR) and the corresponding [hierarchical VQVAE training code](https://github.com/FoundationVision/vaex). I think it may be better than MaskGIT.

**Comment by ericjang** [comment]
Thanks @StarCycle for the recommendations on the encoders. We're not ready to release raw data yet, but please let us know if there are any alternate tokenizers you think would work better. We'll release a fine-tuned MagVIT2 encoder for v1.0 of the dataset release, which is of acceptable quality.
