### ISSUE TITLE
How do you compress an action of a humanoid to an integer id in range [0, 1000]?

### ISSUE THREAD

**Issue by StarCycle** [1x-technologies/1xgpt#4]
Hello,

I check the vector quantinized actions in the dataset. Surprisingly, an action is quantinized to only an integer id in range [0, 1000]. The compression ratio is quite high since a humanoid has so many joints...

How do you quantinized the actions? Do you train an action encoder-decoder like DeepMind's Genie (so the action in dataset is only a latent action and has no relation with real actions of humanoid joints)?

Best,
StarCycle

**Comment by kev-zhao** [comment]
Hello StarCycle,

Our current method of quantizing actions is simply an autoencoder with [FSQ](https://arxiv.org/pdf/2309.15505) applied to the latent space. We are discretizing the actual humanoid actions, not learning latent actions like GENIE. We are considering releasing the raw actions and should have more information within 2 weeks.

**Comment by StarCycle** [comment]
Hi @kev-zhao,

I see. But quantizing float number actions of so many joints to a singe integer between 0 and 1000 still sounds crazy...

Just curious: is it possible to train humanoid policy whose output is the latent action (i.e., the integer id), and then recover this latent action to continuous actions? What's the success rate of this policy?

A similar research is [vqbet](https://arxiv.org/abs/2403.03181). It does compress the action but also predicts continuous number directly.

Looking forward to your response!

**Comment by Guitaricet** [comment]
I believe we don't use all joints for these actions, but a (relatively large) subset that is enough for both manipulation and navigation tasks. Plus, not all of the possible combinations of values are 1) physically possible 2) useful 3) present in the data, which makes the compression to 1000 values more realistic.
We are looking at alternative quantizers though.

**Comment by StarCycle** [comment]
So some joint angles decoded from the action id may be not physical possible. That makes a lot of sense.

Would you like to compress joints to multiple integer ids, instead of a single one. And also use such action representation to train robotics policy?

**Comment by StarCycle** [comment]
@Guitaricet @kev-zhao @ericjang ,

Would you like to try [this](https://arxiv.org/pdf/2310.11731) as a new action tokenizer?

![图片](https://github.com/1x-technologies/1xgpt/assets/33491471/d305bbb5-28a1-4230-afda-c84e704a8539)

**Comment by StarCycle** [comment]
Hi @Guitaricet,

I agree. I do like code-free algorithms like FSQ! 

For SAQ, the core idea is to use state-conditioned action encoder and decoder which may compresses the actions better. Looking forward to your results!

─=≡Σ((( つ•̀ω•́)つ
