### ISSUE TITLE
What's the meaning of `segment_ids` in the dataset?

### ISSUE THREAD

**Issue by StarCycle** [1x-technologies/1xgpt#5]
Hello,

I check the `segment_ids` in your dataset:

```
(Pdb) train_dataset.segment_ids[960:1050]
memmap([341, 341, 341, 341, 341, 341, 341, 341, 301, 301, 341, 341, 341,
        341, 341, 341, 341, 341, 301, 301, 341, 341, 341, 341, 341, 341,
        341, 341, 301, 301, 341, 341, 341, 341, 341, 341, 341, 341, 301,
        301, 341, 341, 341, 341, 341, 341, 341, 301, 301, 301, 341, 341,
        341, 341, 341, 341, 341, 301, 301, 301, 341, 341, 341, 341, 341,
        341, 341, 301, 301, 301, 341, 341, 341, 341, 341, 341, 341, 301,
        301, 301, 341, 341, 341, 341, 341, 341, 341, 301, 301, 301],
       dtype=uint16)
```

If I understand correctly, it means the sample comes from episode `341` and `301`, respectively. The samples come from episode `341` are continuous, even if some samples from episode `301` are among them. Is my understanding correct here?

Best,
StarCycle

**Comment by kev-zhao** [comment]
Hi StarCycle,

Thanks for the question. I believe the `RawTokenDataset` we provide does not have a `segment_ids` field, so I assume you have modified some code. It looks like your "segment_ids" are actions, as the values from your code snippet match the actions at those indices.

The actual segment ids -- `segment_ids.bin` in `data/train_v0` and `data/val_v0` -- should be nondecreasing. Frames with the same segment id are continuous and part of the same episode.

See [`seg_ids` in `RawTokenDataset.__init__`](https://github.com/1x-technologies/1xgpt/blob/05d1197486e4d683e9d58638963ed8a8d4d68ec5/data.py#L41) for an example of loading segment ids, note that it is `int32`.

**Comment by StarCycle** [comment]
Hi @kev-zhao,

I see. Sorry there is an error in my code...Thanks!
