### ISSUE TITLE
Would you like to release the checkpoints of the genie or llama3 models?

### ISSUE THREAD

**Issue by StarCycle** [1x-technologies/1xgpt#6]
Hi @kev-zhao,

Would you like to release the checkpoints of the genie or llama3 models? Then we can quicklot start from finetuning your models of simply move weights of some layers from your models to ours.

Best,
StarCycle

**Comment by kev-zhao** [comment]
Hi StarCycle,

I realize this was not explicitly stated this in the README, but the `User` column on the current [leaderboard](https://github.com/1x-technologies/1xgpt/tree/main?tab=readme-ov-file#leaderboard) corresponds to the HuggingFace model name. The README has [example](https://github.com/1x-technologies/1xgpt/blob/05d1197486e4d683e9d58638963ed8a8d4d68ec5/README.md?plain=1#L61) [code](https://github.com/1x-technologies/1xgpt/blob/05d1197486e4d683e9d58638963ed8a8d4d68ec5/README.md?plain=1#L81) to load and run these two checkpoints.

We will likely update the README to make this clearer in the future!

**Comment by StarCycle** [comment]
I see. Thank you for your response!
