### ISSUE TITLE
Image encoder

### ISSUE THREAD

**Issue by jacob-zietek** [1x-technologies/1xgpt#8]
Hello, 

Will you be releasing the encoder you used to create the image patches? It would be useful for training with external data.

Thank you,
Jacob Zietek

**Comment by kev-zhao** [comment]
Hello Jacob,

Yes, we are happy to release the image encoder. However, we are currently experimenting with different image encoders, so there may be an update to the encoder and dataset soon. I should have an update for you in the next week.

**Comment by kev-zhao** [comment]
Hello again Jacob, we plan to release a new image encoder/decoder and encoded datasets in this coming week.

**Comment by jacob-zietek** [comment]
Thanks Kevin!

**Comment by NamanSharma5** [comment]
@kev-zhao Any chance you can release the raw video files/ frames, I understand the privacy concerns etc. (I guess any good decoder would be able to get a decent output frame, so there would always be some kind of information leak there) but from a research/iteration standpoint it does allow a lot more scope for experimentation with different end-to-end architectures as opposed to just a dynamics model

**Comment by ericjang** [comment]
@NamanSharma5 we're not ready to release raw data yet, as the focus of the World Model Challenge is to improve dynamics prediction (under a fixed encoder). By designing the challenge with fixed encoding of tokens, it makes it easier for participants with only 1 GPU to get some decent results and focus on what we care about (forward prediction).

We might revisit this decision if we find that the sampling challenge really requires raw data to be meaningful (e.g. stable video diffusion). But in the meantime, you can reconstruct the images lossily by using the v1.0 decoder.

**Comment by kev-zhao** [comment]
Hello Jacob,

To address your original question, the image encoder and decoder is included as `magvit2.ckpt` in our v1.0 dataset. Here is an example code snippet applying the image encoder to a batch of raw images:

```python
# `raw_imgs` is a FloatTensor of size (batch_size, 3, 256, 256), with pixel values between [0, 1].

from magvit2.models.lfqgan import VQModel
from magvit2.config import VQConfig

tokenizer = VQModel(VQConfig(), ckpt_path="data/magvit2.ckpt")  # No EMA weights
quant, _, _, _ = tokenizer.encode(raw_imgs * 2 - 1)  # Encoder expects pixel values between [-1, 1]
token_ids = tokenizer.quantize.bits_to_indices(quant.permute(0, 2, 3, 1) > 0).cpu().numpy()

# `token_ids` has shape (batch_size, 16, 16), with values between [0, 2^18 - 1)
```

You may want your external dataset to be compatible with `RawTokenDataset`, in which case you need:
- `video.bin`: You can create the memory-mapped array with: 
`video_data = np.memmap("external_data/video.bin", dtype=np.uint32, mode="w+", shape=(num_images, 16, 16))`
and iteratively write `token_ids` to it.

- `metadata.json`: You can probably copy the `metadata.json` from `train_v1.0/` and update `num_images`.
- Optionally, `segment_ids.bin`, which can be created in a similar way as `video.bin` except with dtype `np.int32` and shape `(num_images,)`.

Please let me know if you want more help on any of these steps.
